version: '3.4'
  

services:
  ims.webapp:
    container_name: ims.app
    image: ${DOCKER_REGISTRY-}imswebapp
    build:
      context: .
      dockerfile: IMS.WebApp/Dockerfile
    ports:
     - "8001:80"
    #environment:
    # - DB_HOST=ims-db
    # - DB_NAME=ims-app
    # - DB_SA_PASSWORD=test123
    depends_on:
     - ims.db
  ims.db:
    restart: on-failure
    container_name: ims.db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
     - "8002:1433"
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_SA_PASSWORD=Test1234
    volumes:
     - ims-db:/var/lib/sqlserver/data
volumes:
  ims-db:

